-- users table (sample domain). Portable SQL except the auto-increment PK,
-- which has no spelling common to SQLite and PostgreSQL. On a PostgreSQL
-- swap, change "INTEGER PRIMARY KEY" to
-- "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"
-- (see docs/ELASTIC_DEPLOYMENT.md, Stage 1 review).
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY,
    name          TEXT    NOT NULL,
    email         TEXT    NOT NULL UNIQUE,
    password_hash TEXT    NOT NULL,
    roles         TEXT    NOT NULL DEFAULT '["user"]'
);
