-- users table (auth domain). Written explicitly for SQLite default.
-- On a PostgreSQL swap, rewrite the autoincrement primary key:
--   Change "INTEGER PRIMARY KEY" -> "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"
--   (or "SERIAL PRIMARY KEY"). See docs/ELASTIC_DEPLOYMENT.md Stage 1.
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY,
    name          TEXT    NOT NULL,
    email         TEXT    NOT NULL UNIQUE,
    password_hash TEXT    NOT NULL,
    roles         TEXT    NOT NULL DEFAULT '["user"]'
);
