import os
from core.base_tool import BaseTool

class ContextTool(BaseTool):
    @property
    def name(self) -> str:
        return "context_manager"

    def setup(self):
        """Does not require technical initialization of external resources."""
        pass

    def get_interface_description(self) -> str:
        return "Automatically generates the AI_CONTEXT.md manifest that serves as a technical manual for AI."

    def on_boot_complete(self, container):
        """Generates the manifest using the Core's internal Registry."""
        
        # The registry is now a GUARANTEE in the container (Core)
        registry = container.registry
        
        # 1. Header and Architecture Rules
        manifest = "# 📜 SYSTEM MANIFEST FOR AI AGENT\n\n"
        manifest += "> **NOTICE:** This file is auto-generated by the Kernel. Do not edit manually.\n\n"
        
        manifest += "## 🧭 Navigation Index (Router)\n"
        manifest += "Before reading further, jump to the section relevant to your task:\n\n"
        manifest += "- **Task: New Infrastructure** → [Available Tools](#-available-tools)\n"
        manifest += "- **Task: Business Feature** → [How to Build a Plugin](#-how-to-create-a-new-domain--plugin)\n"
        manifest += "- **Task: Domain Data** → [Domain Models](#-domain-models-data-structures)\n"
        manifest += "- **Step-by-Step Guide** → [Read INSTRUCTIONS_FOR_AI.md](INSTRUCTIONS_FOR_AI.md)\n\n"

        manifest += "## 🏗️ Philosophy and Architecture\n"
        manifest += "- **Resilient Core**: The Kernel and Container are the stable heart.\n"
        manifest += "- **Lifecycle**: `setup` (Tools) -> `__init__` (Plugins) -> `on_boot` (Registration) -> `execute` (Action).\n"
        manifest += "- **Dependency Injection**: Plugins receive tools in the constructor. **Check signatures below.**\n\n"

        manifest += "## 🚀 How to create a new Domain & Plugin\n"
        manifest += "To extend the system, follow this pattern:\n\n"
        manifest += "1. **Create Directory**: `domains/[domain_name]/plugins/`\n"
        manifest += "2. **Plugin Lifecycle Pattern**:\n"
        manifest += "```python\n"
        manifest += "from core.base_plugin import BasePlugin\n\n"
        manifest += "class MyNewPlugin(BasePlugin):\n"
        manifest += "    def __init__(self, logger, event_bus, http, db): # 1. DI Phase\n"
        manifest += "        self.logger = logger\n"
        manifest += "        self.bus = event_bus\n"
        manifest += "        self.http = http\n"
        manifest += "        self.db = db\n\n"
        manifest += "    def on_boot(self): # 2. Registration Phase\n"
        manifest += "        self.http.add_endpoint('/my/path', 'GET', self.handler)\n"
        manifest += "        self.bus.subscribe('some.event', self.execute)\n\n"
        manifest += "    def execute(self, data=None): # 3. Action Phase\n"
        manifest += "        self.logger.info('Performing work...')\n"
        manifest += "        return {'success': True}\n\n"
        manifest += "    def handler(self, data, context):\n"
        manifest += "        return self.execute(data)\n"
        manifest += "```\n\n"
        
        manifest += "---\n\n"

        # 2. Dynamic Tool Listing
        manifest += "## 🛠️ Available Tools\n"
        manifest += "**Injection Rule**: Request tools by name in your `__init__` constructor.\n\n"
        
        for name in container.list_tools():
            tool = container.get(name)
            health = container.get_health(name)
            status_emoji = "✅" if health["status"] == "OK" else "❌"
            
            manifest += f"### 🔧 Tool: `{name}` (Status: {status_emoji})\n"
            manifest += "**Caps:**\n"
            manifest += f"```text\n{tool.get_interface_description().strip()}\n```\n"
            manifest += "\n"
        
        # 3. Domain Models
        manifest += "## 📦 Domain Models (Data Structures)\n"
        manifest += "Registered data. Read code at paths below for full schemas.\n\n"
        
        domain_metadata = registry.get_domain_metadata()
        for domain_name, data in sorted(domain_metadata.items()):
            manifest += f"### 🧩 Domain `{domain_name}`\n"
            for key in sorted(data.keys()):
                if key.startswith("model_"):
                    model_name = key.replace("model_", "")
                    manifest += f"- Model: `{model_name}`\n"
            manifest += "\n"

        # 4. Write the file
        try:
            with open("AI_CONTEXT.md", "w", encoding="utf-8") as f:
                f.write(manifest)
        except Exception as e:
            print(f"[ContextTool] Error writing manifest: {e}")